### ISSUE TITLE
"unauthorized" on logout with no indication why

### ISSUE THREAD

**Issue by yaleman** [pfzetto/axum-oidc#15]
I'm trying to work out why I just get an "unauthorized" response on hitting the logout endpoint, I implemented it per the examples:

https://github.com/yaleman/maremma/blob/dad5b1655ce591f8105dcd3824693992628183ea/src/web/mod.rs#L106-L115

and 

https://github.com/yaleman/maremma/blob/dad5b1655ce591f8105dcd3824693992628183ea/src/web/oidc.rs#L15-L27

I don't even see it triggering the span for the logout function so it seems to be happening in the Extractor? I can log in, and it's showing data from the claims on the pages that request them, but just dropping an "unauthorized" without any kind of (even trace-level) logging doesn't give me much to work with sadly 😢

**Comment by yaleman** [comment]
Though... I think I might be misunderstanding this and I just need to clear the tower session to log the user out..

**Comment by pfzetto** [comment]
Hello,
currently the OidcRpInitiatedLogout-Extractor only succeeds if the user has a valid session, otherwise it fails with "unauthorized".
You're using the OidcAuthLayer-Middleware, which only extracts valid sessions but doesn't initiates new logins.
The OidcLoginLayer-Middleware will start  a new login if no valid session is found.

I will need to think about a better / more obvious / better documented approach, because the current one can be quite confusing.

**Comment by yaleman** [comment]
I have a valid session, which is showing in the claims and session details, which makes it even more confusing 😄

**Comment by pfzetto** [comment]
Mhh, this seems strange.
Does your issuer support RP-Initiated Logout?
Your issuer should support it if it includes the `end_session_endpoint` in the `/.well-known/openid-connect` response.

**Comment by yaleman** [comment]
I think the confusion is that I expected to be able to send a user direct to the endpoint, rather than through the IdP - it's not clear from the examples

**Comment by yaleman** [comment]
Because if the library is forcing an unauthorized response when it's unable to detect IdP support (with no error/debug/trace logging about it) that makes the problem harder to track down

**Comment by pfzetto** [comment]
Yeah, the documentation and error handling needs work.

You need to send the user directly to your Endpoint that responds with `OidcRpInitiatedLogout`.
With RP-Initiated Logout the client is then directed to the identity provider to revoke the Token and log out the session (So `OidcRpInitiatedLogout` is basically `Redirect::temporary("<end_session_endpoint>?<args>")`).

**Comment by pfzetto** [comment]
With [202b61fa8375dc2c8ab10d244fc36b220434e890](https://github.com/pfzetto/axum-oidc/commit/202b61fa8375dc2c8ab10d244fc36b220434e890) this error is now handled explicitly (as it should be).
