### ISSUE TITLE
Enable custom client values / CA trust issues

### ISSUE THREAD

**Issue by Gabgobie** [pfzetto/axum-oidc#17]
Hi,

first of all I'd like to thank you for creating this library. I was just looking to implemnet this in my hobby project when I hit a wall with certificate validity. In my development environment, I am using a custom CA. While this CA is in my system's trust store, reqwest 0.11 doesn't recognize it as they added support for the system's trust store through a breaking change somewhere in 0.12, if I am not mistaken.

Even in version 0.11 however, they do support adding your custom trust through the `Client::builder()`. Unfortunately, this library hardcodes the defaults.

https://github.com/pfzetto/axum-oidc/blob/202b61fa8375dc2c8ab10d244fc36b220434e890/src/lib.rs#L144

I'd like to suggest/request bumping the reqwest version for system trust support or granting the library consumer access to the `Client::builder()`.

Since I am very new to Rust development, there may be mistakes in my assessment.

Best,
Gab

**Comment by Gabgobie** [comment]
I tried some things and as it seems it is sufficient to add the `native-tls` feature to the dependencies:

`reqwest = { version = "0.11", default-features = false, features = [ "native-tls" ] }`

and change the above linked line to:

`let client = reqwest::Client::builder().use_native_tls().build().unwrap();`

With that it's working without any further changes necessary. Is it possible to influence a crate in this way from my application or will I need to maintain a local fork? Will you consider adding this functionality in this crate?

Best,
Gab

**Comment by pfzetto** [comment]
Hello,
sorry for the delayed response.
You should be able to use `OidcClient::discover_new_with_client` to pass a custom `request::Client` for communication with the issuer.

**Comment by Gabgobie** [comment]
Hi. Thanks for your response and no worries! Going by the example that would be here, right?

https://github.com/pfzetto/axum-oidc/blob/9dd85a770357eb2718b4117836c3b23482766c2d/examples/basic/src/lib.rs#L38-L47

**Comment by pfzetto** [comment]
Yes, that ia correct.

**Comment by Gabgobie** [comment]
Perfect, thanks!
