### ISSUE TITLE
Replace `openidconnect::reqwest::async_http_client` with custom reqwest client

### ISSUE THREAD

**Issue by heimmat** [pfzetto/axum-oidc#18]
Circling back to #12 I did encounter a new blocker.

While the discovery now works, I still encounter certificate issues which I trace back to your usage of `openidconnect::reqwest::async_http_client` in middleware.rs.
Apparently, client discovery is **not** the only time my application will directly contact the OIDC server. 

Do you see a way to also insert a custom reqwest::Client there?

**Comment by pfzetto** [comment]
Hello,
this seems to be a bug. The `request::Client` should be stored in `OidcClient` and used in the middleware.

**Comment by pfzetto** [comment]
Hello,
please try 9dd85a770357eb2718b4117836c3b23482766c2d (currently on master).

**Comment by heimmat** [comment]
I updated my Cargo.toml and this seems to just work as expected. Thanks a lot for your quick help!  

Do you have any plans yet for when you'll release to crates.io?
