### ISSUE TITLE
SessionNotFound on "maybe_authenticated" example with tower-sessions 0.13.0

### ISSUE THREAD

**Issue by yaleman** [pfzetto/axum-oidc#19]
This might need fixing after ... whatever's recently changed in `tower-sessions` - 0.13.0 just throws `SessionNotFound` and dies.

I've tried setting the `with_always_save` to true and it still doesn't work, anyone have an idea how to fix it?

**Comment by pfzetto** [comment]
Do you have updated the Version in the Cargo.toml of axum-oidc? Currently it only supports 0.12.x.

**Comment by yaleman** [comment]
I'm just going by released crates, as usual with tower there's only a vague reference as to what's changed in the upstream packages with no indication of what's going to break, or what it's compatible with 😭

**Comment by FloRide1** [comment]
> Do you have updated the Version in the Cargo.toml of axum-oidc? Currently it only supports 0.12.x. Technically it should work but not everybody is following semver. I will take a look if I can update to 0.13.0

I've tried it and it work fine, i don't understand what may cause this bug, but just bumping the version of axum-oidc seems to fix it

**Comment by pfzetto** [comment]
v0.5.0 is updated to use `tower-sessions` v0.13

**Comment by edgsousa** [comment]
This happens again with tower-sessions 0.14
