### ISSUE TITLE
New tower/tower-session versions doesn't compile with axum-oidc examples

### ISSUE THREAD

**Issue by aellwein** [pfzetto/axum-oidc#6]
Problem i've encountered: 
if upgraded to tower 0.4 and tower-sessions 0.11, users of the axum-oidc libary (not the library itself) do not compile anymore.

To illustrate this, i've added [an example](https://github.com/aellwein/axum-oidc/blob/master/examples/simple.rs) to my fork and a a [CI/CD to build](https://github.com/aellwein/axum-oidc/blob/master/.github/workflows/ci.yml), which is failing for the example
with [error output](https://github.com/aellwein/axum-oidc/actions/runs/8203367133/job/22435991750#step:4:401).

Another problem is that example in README is "lying"; that's not related to it, but it doesn't compile out-of-the-box (you'll find out if you invoke ``cargo test`` which runs doctests automatically).

**Comment by pfz4** [comment]
Thanks for raising the issue,
I will update the versions and add a CI pipeline to the project after looking at yours. 
To ensure that the example is valid, I will move it to an examples folder in the repo and remove it from the Readme.

The changes will be published before Monday.

**Comment by pfzetto** [comment]
Please test with the current version (2741a3ee28660ec912dfde9779af187dd74e916c).
If that works, I will publish a new version to crates.io

**Comment by aellwein** [comment]
@pfzetto i've just tested it, it works as expected. Thanks!

**Comment by pfzetto** [comment]
I've now published it as `0.3.0` on https://crates.io
