### ISSUE TITLE
[FEAT] Logout

### ISSUE THREAD

**Issue by FloRide1** [pfzetto/axum-oidc#7]
Hi,

A logout (as an endpoint) feature would be great. I know that you can just `Redirect::to(issuer + /protocol/open-id-connect/logout)`, but adding something allowing this comportment would be great :).

**Comment by pfzetto** [comment]
Good Idea,
I think I will add another OIDCLogout extractor that also implements a responder to initiate a front channel logout.
I will have to look in the spec how I can pass a redirect URI to the logout and implement it next week.

**Comment by pfzetto** [comment]
Hello,
I've pushed a first implementation of [RP Initiated Logout](https://openid.net/specs/openid-connect-rpinitiated-1_0.html) to the branch [`rp-initiated-logout`](https://github.com/pfzetto/axum-oidc/tree/rp-initiated-logout).

I don't think that the API will change much, but it still needs work (adding comments and documentation, replacing unwrap with proper error handling and reducing the number of clones, etc.).

**Comment by FloRide1** [comment]
Looks great :smile:

**Comment by pfzetto** [comment]
Now on `master`. I will wait updating crates.io until `openidconnect` supports `reqwest 0.12`.

**Comment by FloRide1** [comment]
:smile: i think i can close, just waiting for the crates.io update (i saw for openidconnect / reqwest message). Thanks that was quick.
